[package]
name = "fedimint-lnv2-common"
version = { workspace = true }
authors = ["The Fedimint Developers"]
edition = "2021"
description = "fedimint-ln is a lightning payment service module."
license = "MIT"

[package.metadata.cargo-udeps.ignore]
# cargo udeps can't detect that one
normal = ["aquamarine"]

[lib]
name = "fedimint_lnv2_common"
path = "src/lib.rs"

[dependencies]
anyhow = { workspace = true }
bitcoin = { workspace = true }
bitcoin30 = { workspace = true }
bitcoin_hashes = { workspace = true }
fedimint-core = { workspace = true }
fedimint-ln-common = { workspace = true }
group = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tpe = { workspace = true }
