[package]
authors = { workspace = true }
description = "Experimental Simplicity contract module: client"
edition = { workspace = true }
license = { workspace = true }
name = "fedimint-simplicity-client"
readme = { workspace = true }
repository = { workspace = true }
version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
bitcoin = { workspace = true }
erased-serde = { workspace = true }
fedimint-aead = { workspace = true }
fedimint-api-client = { workspace = true }
fedimint-client-module = { workspace = true }
fedimint-core = { workspace = true }
fedimint-derive-secret = { workspace = true }
fedimint-simplicity-common = { workspace = true, features = ["compiler"] }
futures = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
fedimint-connectors = { workspace = true }
serde_json = { workspace = true }

[lints]
workspace = true
